name: Test

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install server dependencies
        run: yarn install

      