name: Client

on:
  push:
    branches: ["nafisa"]
  pull_request:
    branches: ["nafisa"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Move to client
        uses: cd client

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install client dependencies
        run: yarn install

      - name: Run server tests
        run: yarn run test
