name: Client CI

on:
  push:
    branches:
      - staging
      - nafisa
    paths:
      - "client/**"
  pull_request:
    branches:
      - staging
      - nafisa
    paths:
      - "client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install client dependencies
        run: yarn install

    #   - name: Run server tests
    #     run: yarn run test
