name: Server CI

on:
  push:
    branches:
      - staging
      - nafisa
    paths:
      - "server/**"
  pull_request:
    branches:
      - staging
      - nafisa
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5


